# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def even_valued_fib(max_number):
  a0 = 1
  a1 = 2
  aTemp = 0
  fib_sum = 0

  while a1 <= max_number:
    if a1 % 2 == 0:
      fib_sum += a1

    aTemp = a1
    a1 += a0
    a0 = aTemp

  return fib_sum

m = 4000000
print "Even Fibonacci sum up to %d: %d", m, even_valued_fib(m)